reload "user.plugins"
reload "user.options"
reload "user.keymaps"
reload "user.autocommands"
reload "user.lsp"
reload "user.smoothie"
reload "user.harpoon"
reload "user.bookmark"
reload "user.todo-comments"
reload "user.fidget"
reload "user.git"
reload "user.zen-mode"
reload "user.inlay-hints"
reload "user.telescope"
reload "user.bqf"
reload "user.numb"
reload "user.treesitter"
reload "user.colorizer"
reload "user.lualine"
reload "user.scrollbar"
reload "user.zk"
reload "user.whichkey"
reload "user.autopairs"
reload "user.lua_snip"
reload "user.snippets"
reload "user.dap.config"


-- reload "user.illuminate"
-- reload "user.signature-help"
-- reload "user.chatgpt"
-- reload "user.neogit"
-- -- reload "user.dial"
-- -- reload "user.jaq"
-- -- reload "user.lab"
-- -- reload "user.cybu"
-- -- reload "user.surround"
