reload "user.lsp"
reload "user.plugins"
reload "user.autopairs"
reload "user.options"
reload "user.keymaps"
reload "user.autocommands"
reload "user.smoothie"
reload "user.bookmark"
reload "user.todo-comments"
reload "user.git"
reload "user.inlay-hints"
reload "user.telescope"
reload "user.bqf"
reload "user.treesitter"
reload "user.colorizer"
reload "user.lualine"
reload "user.whichkey"
reload "user.lua_snip"
reload "user.snippets"
reload "user.dap_config"
reload "user.femaco"
reload "user.cmp"
reload "user.go_to_preview"
reload "user.hlargs"
reload "user.hurl"
reload "user.obsidian"

-- reload "user.solarized_osaka"
-- reload "user.harpoon"
-- reload "user.zk"
-- reload "user.numb"
-- reload "user.scrollbar"
-- reload "user.fidget"
-- reload "user.headlines"
-- reload "user.chatgpt"
-- reload "user.neoscroll"
-- reload "user.zen-mode"
-- reload "user.illuminate"
-- reload "user.signature-help"
-- reload "user.neogit"
-- -- reload "user.dial"
-- -- reload "user.jaq"
-- -- reload "user.lab"
-- -- reload "user.cybu"
-- -- reload "user.surround"
