vim.api.nvim_set_hl(0, 'EyelinerPrimary', { fg='#ff00ff', bold = true, underline = false })
vim.api.nvim_set_hl(0, 'EyelinerSecondary', { fg='#00ffff', underline = false })
vim.api.nvim_set_hl(0, 'ObsidianBullet', { bold = true, fg = "#89ddff" })
vim.api.nvim_set_hl(0, 'ObsidianTodo', { bold = true, fg = "#f78c6c" })
vim.api.nvim_set_hl(0, 'ObsidianDone', { bold = true, fg = "#89ddff" })
vim.api.nvim_set_hl(0, 'ObsidianRightArrow', { bold = true, fg = "#f78c6c" })
vim.api.nvim_set_hl(0, 'ObsidianTilde', { bold = true, fg = "#ff5370" })
vim.api.nvim_set_hl(0, 'ObsidianImportant', { bold = true, fg = "#d73128" })
vim.api.nvim_set_hl(0, 'ObsidianRefText', { underline = true, fg = "#c792ea" })
vim.api.nvim_set_hl(0, 'ObsidianExtLinkIcon', { fg = "#c792ea" })
vim.api.nvim_set_hl(0, 'ObsidianTag', { italic = true, fg = "#89ddff" })
vim.api.nvim_set_hl(0, 'ObsidianBlockID', { italic = true, fg = "#89ddff" })
vim.api.nvim_set_hl(0, 'ObsidianHighlightText', { bg = "#75662e" })
